/**
 * Base template files for v0 exports
 * These files are NOT included in v0's API response but are required for the project to work
 */

export const TEMPLATE_FILES = {
  // TypeScript config
  'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,

  // Next.js config
  'next.config.ts': `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;`,

  // Tailwind config (Tailwind v4 - simplified)
  'tailwind.config.ts': `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
};
export default config;`,

  // PostCSS config (Tailwind v4 uses @tailwindcss/postcss)
  'postcss.config.js': `module.exports = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};`,

  // Utils file (for cn() function)
  'lib/utils.ts': `import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}`,

  // Globals CSS (Tailwind v4 style)
  'app/globals.css': `@import "tailwindcss";

@theme {
  /* Fonts */
  --font-family-sans: var(--font-sans), ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  
  /* Colors */
  --color-background: 0 0% 100%;
  --color-foreground: 0 0% 3.9%;
  --color-card: 0 0% 100%;
  --color-card-foreground: 0 0% 3.9%;
  --color-popover: 0 0% 100%;
  --color-popover-foreground: 0 0% 3.9%;
  --color-primary: 0 0% 9%;
  --color-primary-foreground: 0 0% 98%;
  --color-secondary: 0 0% 96.1%;
  --color-secondary-foreground: 0 0% 9%;
  --color-muted: 0 0% 96.1%;
  --color-muted-foreground: 0 0% 45.1%;
  --color-accent: 0 0% 96.1%;
  --color-accent-foreground: 0 0% 9%;
  --color-destructive: 0 84.2% 60.2%;
  --color-destructive-foreground: 0 0% 98%;
  --color-border: 0 0% 89.8%;
  --color-input: 0 0% 89.8%;
  --color-ring: 0 0% 3.9%;
  
  /* Border radius */
  --radius: 0.5rem;
}

@media (prefers-color-scheme: dark) {
  @theme {
    --color-background: 0 0% 3.9%;
    --color-foreground: 0 0% 98%;
    --color-card: 0 0% 3.9%;
    --color-card-foreground: 0 0% 98%;
    --color-popover: 0 0% 3.9%;
    --color-popover-foreground: 0 0% 98%;
    --color-primary: 0 0% 98%;
    --color-primary-foreground: 0 0% 9%;
    --color-secondary: 0 0% 14.9%;
    --color-secondary-foreground: 0 0% 98%;
    --color-muted: 0 0% 14.9%;
    --color-muted-foreground: 0 0% 63.9%;
    --color-accent: 0 0% 14.9%;
    --color-accent-foreground: 0 0% 98%;
    --color-destructive: 0 62.8% 30.6%;
    --color-destructive-foreground: 0 0% 98%;
    --color-border: 0 0% 14.9%;
    --color-input: 0 0% 14.9%;
    --color-ring: 0 0% 83.1%;
  }
}`,

  // Package.json with proper dependencies
  'package.json': `{
  "name": "v0-export",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "next": "15.1.6",
    "tailwindcss": "^4.1.9",
    "@tailwindcss/postcss": "^4.1.9",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.5",
    "lucide-react": "^0.469.0",
    "@radix-ui/react-slot": "^1.1.1"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "eslint": "^8",
    "eslint-config-next": "15.1.6"
  }
}`,

  // App layout (if v0 doesn't provide one)
  'app/layout.tsx': `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "v0 Export",
  description: "Generated by v0.dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}`,

  // components.json (shadcn config)
  'components.json': `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/globals.css",
    "baseColor": "slate",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
}`,

  // README
  'README.md': `# v0 Export

This project was generated by v0.dev and exported via the v0 Clone.

## Tech Stack

- **Next.js 15** - React framework
- **React 19** - UI library
- **Tailwind CSS 4** - Utility-first CSS framework
- **TypeScript** - Type safety
- **shadcn/ui** - Component library

## Getting Started

Install dependencies:

\`\`\`bash
npm install
# or
pnpm install
# or
yarn install
\`\`\`

Run the development server:

\`\`\`bash
npm run dev
# or
pnpm dev
# or
yarn dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Tailwind CSS 4

This project uses **Tailwind CSS v4** with the new CSS-first configuration:
- Configuration is in \`app/globals.css\` using \`@theme\` directive
- No PostCSS config needed (Tailwind 4 is a native CSS parser)
- Faster builds and simpler setup

## Deploy

Deploy on [Vercel](https://vercel.com/new):

1. Push this repository to GitHub
2. Import the repository in Vercel
3. Deploy!

## Learn More

- [Next.js Documentation](https://nextjs.org/docs)
- [Tailwind CSS v4 Documentation](https://tailwindcss.com/docs)
- [v0.dev](https://v0.dev)
`,

  // .gitignore
  '.gitignore': `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts`,
}

import { getDynamicShadcnComponents } from './shadcn-registry'

/**
 * Detects and normalizes font imports in layout.tsx files
 * Ensures fonts from next/font/google are properly imported
 */
export function detectAndNormalizeFonts(layoutContent: string): string {
  console.log('🔤 Checking for font imports in layout...')
  
  // Detect font imports from next/font/google
  const fontImportRegex = /import\s+{\s*([^}]+)\s*}\s+from\s+['"]next\/font\/google['"]/g
  const fontMatches = [...layoutContent.matchAll(fontImportRegex)]
  
  if (fontMatches.length === 0) {
    console.log('⚠️  No Google Font imports detected, adding default Inter font')
    // No font found, add Inter as default
    return addDefaultInterFont(layoutContent)
  }
  
  // Extract font names
  const fontsUsed = fontMatches.map(match => {
    const imports = match[1].split(',').map(f => f.trim())
    return imports
  }).flat()
  
  console.log('✅ Detected fonts:', fontsUsed.join(', '))
  
  // Validate that fonts are properly configured
  let normalized = layoutContent
  
  // Check if font variables are properly used in className
  for (const fontName of fontsUsed) {
    const varName = fontName.toLowerCase().replace(/_/g, '')
    const varRegex = new RegExp(`const\\s+${varName}\\s*=\\s*${fontName}\\s*\\(`, 'i')
    
    if (!varRegex.test(normalized)) {
      console.log(`⚠️  Font ${fontName} import found but not initialized`)
    }
  }
  
  // Ensure the layout uses the font variables correctly
  // Fix common issues like missing className or wrong variable references
  if (!normalized.includes('className=') && normalized.includes('<html')) {
    console.log('⚠️  No className found on <html> tag, fonts may not apply')
  }
  
  return normalized
}

/**
 * Adds default Inter font if no fonts are detected
 */
function addDefaultInterFont(layoutContent: string): string {
  console.log('📝 Adding default Inter font import')
  
  // Check if there's already a font import line
  if (layoutContent.includes('next/font/google')) {
    return layoutContent
  }
  
  // Add Inter import after the first import statement
  const lines = layoutContent.split('\n')
  const firstImportIndex = lines.findIndex(line => line.trim().startsWith('import'))
  
  if (firstImportIndex === -1) {
    // No imports found, add at the top
    return `import { Inter } from "next/font/google";\n\nconst inter = Inter({ subsets: ["latin"], variable: "--font-sans" });\n\n${layoutContent}`
  }
  
  // Find the line after the last import
  let lastImportIndex = firstImportIndex
  for (let i = firstImportIndex; i < lines.length; i++) {
    if (lines[i].trim().startsWith('import')) {
      lastImportIndex = i
    } else if (lines[i].trim() && !lines[i].trim().startsWith('import')) {
      break
    }
  }
  
  // Insert font import and initialization
  lines.splice(
    lastImportIndex + 1,
    0,
    '',
    'import { Inter } from "next/font/google";',
    '',
    'const inter = Inter({',
    '  subsets: ["latin"],',
    '  variable: "--font-sans",',
    '});'
  )
  
  let result = lines.join('\n')
  
  // Ensure className is added to html tag if not present
  if (!result.includes('className=') && result.includes('<html')) {
    result = result.replace(/<html([^>]*)>/g, '<html$1 className={inter.variable}>')
  }
  
  return result
}

// Check if a file is likely a base template file that shouldn't be overwritten
export function shouldSkipFile(filePath: string, v0Files: string[]): boolean {
  // If v0 already provided this file, use v0's version
  if (v0Files.includes(filePath)) {
    return true
  }
  return false
}

// Get all template files that should be added to the export
// Now includes dynamic shadcn UI component fetching!
export async function getTemplateFilesForExport(
  v0FilePaths: string[], 
  v0Files?: Array<{ source: string; meta?: { file?: string } }>
): Promise<Record<string, string>> {
  const templatesToAdd: Record<string, string> = {}

  // Add all base template files that v0 didn't provide
  for (const [path, content] of Object.entries(TEMPLATE_FILES)) {
    if (!shouldSkipFile(path, v0FilePaths)) {
      templatesToAdd[path] = content
    }
  }

  // DYNAMIC: Fetch only the shadcn components that are actually imported
  if (v0Files && v0Files.length > 0) {
    console.log('🔍 Analyzing v0 files for shadcn components...')
    const shadcnComponents = await getDynamicShadcnComponents(v0Files)
    
    console.log(`📦 Shadcn components received: ${Object.keys(shadcnComponents).length}`)
    console.log(`📦 Component paths:`, Object.keys(shadcnComponents))
    
    for (const [path, content] of Object.entries(shadcnComponents)) {
      console.log(`  → Checking ${path}, shouldSkip: ${shouldSkipFile(path, v0FilePaths)}`)
      if (!shouldSkipFile(path, v0FilePaths)) {
        templatesToAdd[path] = content
        console.log(`    ✅ Added ${path} (${content.length} chars)`)
      } else {
        console.log(`    ❌ Skipped ${path} (v0 already has it)`)
      }
    }
  }

  console.log(`📂 Final templates to add: ${Object.keys(templatesToAdd).length}`)
  console.log(`📂 UI files in templates:`, Object.keys(templatesToAdd).filter(f => f.startsWith('components/ui/')))

  return templatesToAdd
}

